server:
  port: 8091

spring:
  application:
    name: rabbitmq-springboot2
  rabbitmq:
    host: www.haoxiaoyong.cn
    port: 5672
    username: haoxiaoyong
    password: 12345678
    virtualHost: /
    publisher-confirms: true
    publisher-returns: true

rabbit:
  message_queue: message_queue
  topic_exchange: exchange_topics
  routing_key: rouing_message