server:
  port: 8090

spring:
  application:
    name: rabbitmq-springboot
  rabbitmq:
    host: 47.100.102.136
    port: 5672
    username: haoxiaoyong
    password: ***
    virtualHost: /
    publisher-confirms: true
    publisher-returns: true

myRabbit:
  queue_inform_email: queue_inform_email
  queue_inform_sms: queue_inform_sms
  exchange_topics_inform: exchange_topics_inform
