server:
  port: 8090

spring:
  application:
    name: rabbitmq-producer
  rabbitmq:
    host: www.haoxiaoyong.cn
    port: 5672
    username: guest
    password: guest
    virtualHost: /

myRabbitmq:
  QUEUE_INFORM_EMAIL: queue_inform_email
  QUEUE_INFORM_SMS: queue_inform_sms
  EXCHANGE_TOPICS_INFORM: exchange_topics_inform
  ROUTINGKEY_EMAIL: inform.#.email.#
  ROUTINGKEY_SMS: nform.#.sms.#